image: node:14.18.0
cache:
  paths:
    - node_modules/

before_script:
  - npm install

stages:
  - test
  - deploy

frontend-test:
  stage: test
  script:
    - node --version
  allow_failure: true

pages:
  stage: deploy
  script:
    - npm install -g @angular/cli@12.2.9
    - npm run buildProd
  artifacts:
    paths:
      - public
  only:
    - master
    - pages
